# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bilgie < Formula
  desc "Disk-pressure janitor for dev machines running many agents"
  homepage "https://github.com/smykla-skalski/bilgie"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smykla-skalski/bilgie/releases/download/v0.11.0/bilgie_0.11.0_darwin_amd64.tar.gz"
      sha256 "9d93eb7957fd37ebc9c1df0a92299f1684720128ba0846a1929df380106b2d06"

      define_method(:install) do
        bin.install "bilgie"
        generate_completions_from_executable(bin/"bilgie", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smykla-skalski/bilgie/releases/download/v0.11.0/bilgie_0.11.0_darwin_arm64.tar.gz"
      sha256 "08ae71787221a183c75480be00cc02824feceb16453a8ee83e20ccff0266f7cc"

      define_method(:install) do
        bin.install "bilgie"
        generate_completions_from_executable(bin/"bilgie", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smykla-skalski/bilgie/releases/download/v0.11.0/bilgie_0.11.0_linux_amd64.tar.gz"
      sha256 "4eff3962636a14ca7f4512f578c9bbc9df970e705009c55cceeda8ef07ab857e"
      define_method(:install) do
        bin.install "bilgie"
        generate_completions_from_executable(bin/"bilgie", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smykla-skalski/bilgie/releases/download/v0.11.0/bilgie_0.11.0_linux_arm64.tar.gz"
      sha256 "c53d2b3b4bc5312c03b63a09d43043e497276faff2bc01e247d4f753206f445a"
      define_method(:install) do
        bin.install "bilgie"
        generate_completions_from_executable(bin/"bilgie", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      To start the background janitor:

        bilgie install-agent

      The first run is a dry-run. Check cache sizes with:

        bilgie status
    EOS
  end

  test do
    system "#{bin}/bilgie", "--version"
  end
end
