# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bilgie < Formula
  desc "Disk-pressure janitor for dev machines running many agents"
  homepage "https://github.com/smykla-skalski/bilgie"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smykla-skalski/bilgie/releases/download/v0.10.0/bilgie_0.10.0_darwin_amd64.tar.gz"
      sha256 "88a32fac843ed7a2fe56e80679dea7ad80a9c23f4d02900dd3d59a1e23881548"

      define_method(:install) do
        bin.install "bilgie"
        generate_completions_from_executable(bin/"bilgie", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smykla-skalski/bilgie/releases/download/v0.10.0/bilgie_0.10.0_darwin_arm64.tar.gz"
      sha256 "e209d446eb6eae3f20d6cdb2f9ce4a9e7d358bdd10ebe8f2c172c47deb0227f8"

      define_method(:install) do
        bin.install "bilgie"
        generate_completions_from_executable(bin/"bilgie", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smykla-skalski/bilgie/releases/download/v0.10.0/bilgie_0.10.0_linux_amd64.tar.gz"
      sha256 "d271df4ed3bf65a5a1d2d5f86178b1c36591e9abc88f96c3a9ca4c40409b3bee"
      define_method(:install) do
        bin.install "bilgie"
        generate_completions_from_executable(bin/"bilgie", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smykla-skalski/bilgie/releases/download/v0.10.0/bilgie_0.10.0_linux_arm64.tar.gz"
      sha256 "498d397ce415c1c10387e5fdd6b3a8454e55d90d7024ee9069abc3a777e7d827"
      define_method(:install) do
        bin.install "bilgie"
        generate_completions_from_executable(bin/"bilgie", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      To start the background janitor:

        bilgie install-agent

      The first run is a dry-run. Check cache sizes with:

        bilgie status
    EOS
  end

  test do
    system "#{bin}/bilgie", "--version"
  end
end
