# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Klaudiush < Formula
  desc "Validation dispatcher for Claude Code hooks"
  homepage "https://github.com/smykla-skalski/klaudiush"
  version "1.44.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smykla-skalski/klaudiush/releases/download/v1.44.0/klaudiush_1.44.0_darwin_amd64.tar.gz"
      sha256 "739beb0a6c75d2da820f67a902747d2e0e4b7cb86c4656a3f25882536dbb6b7d"

      define_method(:install) do
        bin.install "klaudiush"
        generate_completions_from_executable(bin/"klaudiush", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smykla-skalski/klaudiush/releases/download/v1.44.0/klaudiush_1.44.0_darwin_arm64.tar.gz"
      sha256 "2b21e9a0ad21712611b5d7ee17f6a5b6c0e05f70a9fbafaaf49716c9236368da"

      define_method(:install) do
        bin.install "klaudiush"
        generate_completions_from_executable(bin/"klaudiush", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smykla-skalski/klaudiush/releases/download/v1.44.0/klaudiush_1.44.0_linux_amd64.tar.gz"
      sha256 "2c3486519884d54fd5ff692f26aa21e6ee5a4b97056fda75c035cf90f64a79a9"
      define_method(:install) do
        bin.install "klaudiush"
        generate_completions_from_executable(bin/"klaudiush", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smykla-skalski/klaudiush/releases/download/v1.44.0/klaudiush_1.44.0_linux_arm64.tar.gz"
      sha256 "34d4ed8d0c0a25546ce6a1fb6c275324b188c20f893bc11d96b9f1f180fe0681"
      define_method(:install) do
        bin.install "klaudiush"
        generate_completions_from_executable(bin/"klaudiush", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      To enable klaudiush as a Claude Code hook dispatcher:

        klaudiush init --global

      Documentation: https://github.com/smykla-skalski/klaudiush
    EOS
  end

  test do
    system "#{bin}/klaudiush", "--version"
    system "#{bin}/klaudiush", "doctor", "--help"
  end
end
