# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Klaudiush < Formula
  desc "Validation dispatcher for Claude Code hooks"
  homepage "https://github.com/smykla-skalski/klaudiush"
  version "1.31.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smykla-skalski/klaudiush/releases/download/v1.31.1/klaudiush_1.31.1_darwin_amd64.tar.gz"
      sha256 "cc897f070de8e5af78a1c2a6afedb636de3f1b554eb512c65311041afa2814e4"

      define_method(:install) do
        bin.install "klaudiush"
        generate_completions_from_executable(bin/"klaudiush", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smykla-skalski/klaudiush/releases/download/v1.31.1/klaudiush_1.31.1_darwin_arm64.tar.gz"
      sha256 "a3d78c006127def0285122e83e6596c88b3c82ea531a6d85833166cfced2238f"

      define_method(:install) do
        bin.install "klaudiush"
        generate_completions_from_executable(bin/"klaudiush", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smykla-skalski/klaudiush/releases/download/v1.31.1/klaudiush_1.31.1_linux_amd64.tar.gz"
      sha256 "577fa8293f10256f209c565d40eb831e01eb52338619101b798dbbb6d315a178"
      define_method(:install) do
        bin.install "klaudiush"
        generate_completions_from_executable(bin/"klaudiush", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smykla-skalski/klaudiush/releases/download/v1.31.1/klaudiush_1.31.1_linux_arm64.tar.gz"
      sha256 "0166379fc7ca43006497c08b8af9e9d8f2e68b37d3baaa06a05effd4fb9f42c1"
      define_method(:install) do
        bin.install "klaudiush"
        generate_completions_from_executable(bin/"klaudiush", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      To enable klaudiush as a Claude Code hook dispatcher:

        klaudiush init --global

      Documentation: https://github.com/smykla-skalski/klaudiush
    EOS
  end

  test do
    system "#{bin}/klaudiush", "--version"
    system "#{bin}/klaudiush", "doctor", "--help"
  end
end
